(() => {
  const $ = (s, p=document) => p.querySelector(s);
  const esc = v => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const categories = ['Все', ...new Set(TOPICS.map(t=>t.category))]; let filter='Все';
  $('#topic-count').textContent = TOPICS.length;
  const grid = $('#topic-grid'), testGrid=$('#test-grid');
  function renderTopics(){ const list=filter==='Все'?TOPICS:TOPICS.filter(t=>t.category===filter); grid.innerHTML=list.map(t=>`<article class="topic-card"><div class="topic-icon">${t.icon}</div><span class="tag">${t.category}</span><h3>${t.title}</h3><p>${t.intro}</p><button class="text-button" data-open="${t.id}">Открыть урок <span>→</span></button></article>`).join(''); }
  $('#filters').innerHTML=categories.map(c=>`<button class="filter ${c===filter?'active':''}" data-filter="${c}">${c}</button>`).join(''); renderTopics();
  $('#filters').addEventListener('click', e=>{if(!e.target.dataset.filter)return;filter=e.target.dataset.filter;[...$('#filters').children].forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));renderTopics()});
  function renderTests(){testGrid.innerHTML=TOPICS.map(t=>`<article class="mini-test" data-test="${t.id}"><div><span class="tag">${t.title}</span><h3>${t.mini.prompt}</h3></div><div class="mini-options">${t.mini.options.map((o,i)=>`<button data-choice="${i}">${esc(o)}</button>`).join('')}</div><p class="feedback" aria-live="polite"></p></article>`).join('')}; renderTests();
  document.addEventListener('click',e=>{const open=e.target.closest('[data-open]'); if(open) showLesson(TOPICS.find(t=>t.id===open.dataset.open)); const opt=e.target.closest('.mini-options button');if(opt){const card=opt.closest('.mini-test'),t=TOPICS.find(x=>x.id===card.dataset.test),ok=+opt.dataset.choice===t.mini.answer;card.querySelectorAll('button').forEach(b=>b.disabled=true);opt.classList.add(ok?'correct':'incorrect');card.querySelector('.feedback').textContent=ok?'Верно! Отличное начало.':'Пока нет. Правильный ответ: '+t.mini.options[t.mini.answer];}});
  const input=$('#search-input'), suggestions=$('#suggestions');
  function matches(q){q=q.toLowerCase().trim(); return TOPICS.filter(t=>[t.title,...t.aliases,t.category].join(' ').toLowerCase().includes(q));}
  input.addEventListener('input',()=>{const found=matches(input.value).slice(0,5);suggestions.hidden=!input.value.trim()||!found.length;suggestions.innerHTML=found.map(t=>`<button type="button" data-open="${t.id}"><span>${t.icon}</span>${t.title}<small>${t.category}</small></button>`).join('')||'<p>Тема пока не найдена. Выберите одну из карточек ниже.</p>'});
  $('#topic-search').addEventListener('submit',e=>{e.preventDefault();const found=matches(input.value);if(found[0])showLesson(found[0]);else {suggestions.hidden=false;suggestions.innerHTML='<p>Такой темы пока нет. Попробуйте название из каталога ниже.</p>';}});
  function showLesson(t){
   document.title=`${t.title} — English Studio`; suggestions.hidden=true;
   $('#app').innerHTML=`<section class="lesson-hero"><button class="back" id="back-home">← Все темы</button><p class="eyebrow">${t.category} · урок</p><div class="lesson-title"><div class="lesson-icon">${t.icon}</div><div><h1>${t.title}</h1><p>${t.intro}</p></div></div><nav class="lesson-nav"><a href="#rule">Правило</a><a href="#examples">Примеры</a><a href="#practice">Практика</a></nav></section><section id="rule" class="lesson-section"><p class="eyebrow">01 · Основа</p><h2>Как это работает</h2><p class="rule-text">${t.rule}</p><div class="formula">${t.formula}</div><div class="grammar-table"><div class="table-head"><span>Случай</span><span>Английский</span><span>Перевод</span></div>${t.rows.map(r=>`<div><strong>${r[0]}</strong><span>${r[1]}</span><span>${r[2]}</span></div>`).join('')}</div></section><section id="examples" class="lesson-section examples"><p class="eyebrow">02 · В контексте</p><h2>Живые примеры</h2><div class="example-list">${t.examples.map((x,i)=>`<article><b>0${i+1}</b><blockquote>${x[0]}</blockquote><p>${x[1]}</p></article>`).join('')}</div></section><section id="practice" class="lesson-section practice"><p class="eyebrow">03 · Закрепление</p><h2>Проверьте себя</h2><p>Выберите один ответ для каждого задания.</p><div class="exercise-wrap">${[t.exercise,t.mini].map((q,n)=>`<article class="exercise" data-exercise="${n}"><span class="exercise-num">${n+1}</span><h3>${q.prompt}</h3><div>${q.options.map((o,i)=>`<button data-answer="${i}">${esc(o)}</button>`).join('')}</div><p class="exercise-feedback" aria-live="polite"></p></article>`).join('')}</div></section><section class="lesson-next"><p>Хотите продолжить?</p><h2>Выберите следующую тему</h2><div>${TOPICS.filter(x=>x.id!==t.id).slice(0,3).map(x=>`<button data-open="${x.id}">${x.icon} ${x.title} <span>→</span></button>`).join('')}</div></section>`;
   window.scrollTo({top:0,behavior:'smooth'});
   $('#back-home').onclick=()=>location.reload();
   document.querySelectorAll('.exercise').forEach((card,n)=>card.addEventListener('click',e=>{const b=e.target.closest('[data-answer]');if(!b)return;const q=[t.exercise,t.mini][n],ok=+b.dataset.answer===q.answer;card.querySelectorAll('button').forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'incorrect');card.querySelector('.exercise-feedback').textContent=ok?('Верно! '+(q.explain||'Отличная работа.')):('Не совсем. Верный ответ: '+q.options[q.answer]+'. '+(q.explain||''));}));
  }
})();
